spring:
  application:
    name: nacon7-client                # 客户端服务名
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848   # Nacos 注册中心地址

server:
  port: 8081                           # 客户端端口（避免与服务端 8080 冲突）